### ISSUE TITLE
Unit tests are failing when wagtail >= 2.12

### ISSUE THREAD

**Issue by ColinBeeby-Developer** [wagtail/wagtail-factories#41]
Some of the unit tests are failing when a wagtail version of >=2.12 is installed. The failing tests are **test_custom_page_streamfield_data_complex, test_custom_page_streamfield_default_blocks, test_custom_page_streamfield** and **test_custom_page_streamfield_data**. I've tried running the tests against Wagtail 2.9.3 and 2.11.7 and they pass.
The issue seems to be that an id attribute has been added to the block in Wagtail >= 2.12.
For example the data returned by the MyTestPageWithStreaFieldFactory call, with Wagtail >= 2.12 looks like this (page.body.streamdata): 

`[('char_array', ['foo', 'bar'], '35741861-c5ea-45a9-a8f5-8f5de95fe6d8'), ('struct', StructValue([('title', 'My Title'), ('item', StructValue([('label', 'my-label'), ('value', 100)])), ('items', []), ('image', None)]), 'a99daf3d-9055-45f3-a0f2-3b61fd45f58a'), ('int_array', [100], 'b7b60e57-5df2-4996-9916-d8f132ba57be'), ('image', <Image: Blub>, '4138701b-c8fe-45b9-91f9-6e0cdbcce520')]`

Note the additional guids which are not expected in the test data.

I will try to fix this issue, but I'm looking for some advise on the best way to proceed. Can we simply drop support for older versions of wagtail and modify the unit tests to expect the additional guids? Or do we need to maintain support for older versions of Wagtail and modify the tests to take account of different versions (EG check the Wagtail version)? Or some other option which I have not thought of?

**Comment by marteinn** [comment]
Hi @ColinBeeby-Developer and thank you for raising this issue! 

This error is because of a larger streamfield refactoring that has been done in Wagtail 2.12 and 2.13, where the tests itself are relying on a deprecated property for comparison (`stream_data`), we should instead compare `block_type` and `value` directly on the streamfield property (`page.body[0].block_type == "image"` / `page.body[0].value == [100]`).

As to you questions, we need to keep supporting older Wagtail versions, but only those who are officially supported, those are 2.11 and 2.13 (according to https://github.com/wagtail/wagtail/wiki/Release-schedule).

I'm did not see a PR from you so I'm taking the initiative for a PR so we can get this solved as quick as possible.

**Comment by marteinn** [comment]
Merged in https://github.com/wagtail/wagtail-factories/commit/a28a66eb08503a854ae5f91a36f71bdb01c14a55
